"""Traditional YOLOv5 v7 configuration and deterministic blur snapshot support."""

from __future__ import annotations

import csv
import random
import shutil
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from .config import AugmentationOptions

LEGACY_HYP_BASELINE: Mapping[str, float] = {
    "lr0": 0.01,
    "lrf": 0.01,
    "momentum": 0.937,
    "weight_decay": 0.0005,
    "warmup_epochs": 3.0,
    "warmup_momentum": 0.8,
    "warmup_bias_lr": 0.1,
    "box": 0.05,
    "cls": 0.5,
    "cls_pw": 1.0,
    "obj": 1.0,
    "obj_pw": 1.0,
    "iou_t": 0.2,
    "anchor_t": 4.0,
    "fl_gamma": 0.0,
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.4,
    "degrees": 0.0,
    "translate": 0.1,
    "scale": 0.5,
    "shear": 0.0,
    "perspective": 0.0,
    "flipud": 0.0,
    "fliplr": 0.5,
    "mosaic": 1.0,
    "mixup": 0.0,
    "copy_paste": 0.0,
}

IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}


def legacy_hyp_values(augmentation: AugmentationOptions) -> dict[str, float]:
    augmentation.validate()
    values = dict(LEGACY_HYP_BASELINE)
    if not augmentation.enabled:
        values.update({"degrees": 0.0, "flipud": 0.0, "fliplr": 0.0})
    else:
        values.update(
            {
                "degrees": (
                    augmentation.rotation_degrees
                    if augmentation.rotation_probability > 0
                    else 0.0
                ),
                "flipud": augmentation.flipud,
                "fliplr": augmentation.fliplr,
            }
        )
    return values


def write_legacy_hyp(path: str | Path, augmentation: AugmentationOptions) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated for the official YOLOv5 v7.0 training script.",
        *(
            f"{key}: {_yaml_number(value)}"
            for key, value in legacy_hyp_values(augmentation).items()
        ),
    ]
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return destination


def prepare_legacy_blur_snapshot(
    source_data_yaml: str | Path,
    destination_root: str | Path,
    *,
    probability: float,
    kernel: int,
    seed: int,
) -> Path:
    """Create a runnable YOLO dataset snapshot with deterministic train-only blur.

    This avoids patching the old YOLOv5 dataset implementation.  It supports
    the immutable snapshot layout generated by this application:
    ``images/train``, ``images/val``, ``labels/train`` and ``labels/val``.
    """

    if not 0 < probability <= 1:
        raise ValueError("模糊概率必须在 (0, 1] 内")
    if kernel <= 0 or kernel % 2 == 0:
        raise ValueError("模糊核必须是正奇数")
    try:
        import yaml
        from PIL import Image, ImageFilter
    except ImportError as exc:
        raise RuntimeError("生成 YOLOv5 模糊快照需要 PyYAML 和 Pillow") from exc
    source_yaml = Path(source_data_yaml).resolve()
    raw = yaml.safe_load(source_yaml.read_text(encoding="utf-8"))
    if not isinstance(raw, Mapping):
        raise ValueError("data.yaml 顶层必须是对象")
    dataset_root = Path(str(raw.get("path") or source_yaml.parent))
    if not dataset_root.is_absolute():
        dataset_root = (source_yaml.parent / dataset_root).resolve()
    destination = Path(destination_root).resolve()
    destination.mkdir(parents=True, exist_ok=True)
    rng = random.Random(seed)
    output_yaml: dict[str, Any] = {
        key: value
        for key, value in raw.items()
        if key not in {"path", "train", "val", "test"}
    }
    output_yaml["path"] = str(destination)
    for split in ("train", "val", "test"):
        if split not in raw:
            continue
        relative = Path(str(raw[split]))
        source_images = relative if relative.is_absolute() else dataset_root / relative
        if not source_images.is_dir():
            raise ValueError(
                f"YOLOv5 模糊快照仅支持图片目录形式，{split} 不是目录：{source_images}"
            )
        destination_images = destination / "images" / split
        destination_labels = destination / "labels" / split
        destination_images.mkdir(parents=True, exist_ok=True)
        destination_labels.mkdir(parents=True, exist_ok=True)
        for source_image in sorted(source_images.rglob("*")):
            if not source_image.is_file() or source_image.suffix.casefold() not in IMAGE_SUFFIXES:
                continue
            relative_image = source_image.relative_to(source_images)
            output_image = destination_images / relative_image
            output_image.parent.mkdir(parents=True, exist_ok=True)
            should_blur = split == "train" and rng.random() < probability
            if should_blur:
                with Image.open(source_image) as opened:
                    converted = opened.convert("RGB")
                    converted.filter(
                        ImageFilter.BoxBlur(radius=max(1, (kernel - 1) / 2))
                    ).save(output_image)
            else:
                shutil.copy2(source_image, output_image)
            source_label = _label_for_image(source_image, source_images, dataset_root, split)
            output_label = destination_labels / relative_image.with_suffix(".txt")
            if source_label.is_file():
                output_label.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source_label, output_label)
        output_yaml[split] = f"images/{split}"
    destination_yaml = destination / "data.yaml"
    destination_yaml.write_text(
        yaml.safe_dump(output_yaml, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
        newline="\n",
    )
    return destination_yaml


def read_new_results_rows(
    path: str | Path,
    *,
    after_epoch: int = -1,
) -> list[tuple[int, dict[str, float | str]]]:
    """Read complete YOLOv5 ``results.csv`` rows newer than ``after_epoch``."""

    results_path = Path(path)
    if not results_path.is_file():
        return []
    rows: list[tuple[int, dict[str, float | str]]] = []
    try:
        with results_path.open("r", encoding="utf-8", newline="") as handle:
            for row in csv.DictReader(handle):
                normalized = {str(key).strip(): str(value).strip() for key, value in row.items()}
                epoch_text = normalized.get("epoch")
                if epoch_text in (None, ""):
                    continue
                epoch = int(float(epoch_text))
                if epoch <= after_epoch:
                    continue
                metrics: dict[str, float | str] = {}
                for key, value in normalized.items():
                    try:
                        metrics[key] = float(value)
                    except ValueError:
                        metrics[key] = value
                rows.append((epoch, metrics))
    except (OSError, csv.Error, ValueError):
        return []
    return rows


def _label_for_image(
    image: Path,
    images_root: Path,
    dataset_root: Path,
    split: str,
) -> Path:
    relative = image.relative_to(images_root).with_suffix(".txt")
    candidate = dataset_root / "labels" / split / relative
    if candidate.exists():
        return candidate
    parts = list(image.parts)
    try:
        index = max(i for i, part in enumerate(parts) if part.casefold() == "images")
    except ValueError:
        return candidate
    parts[index] = "labels"
    return Path(*parts).with_suffix(".txt")


def _yaml_number(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else str(value)
