"""Small MaixPy application template and allowlisted app manifest."""

from __future__ import annotations

from collections.abc import Iterable

from ai_biaozhu.ml.model_registry import get_model


def maixpy_main(model_key: str) -> str:
    family = get_model(model_key).family
    detector_class = {
        "yolov5": "YOLOv5",
        "yolov8": "YOLOv8",
        "yolo11": "YOLO11",
        "yolo26": "YOLO26",
    }[family]
    detect_call = (
        'detector.detect(frame, conf_th=config["confidence"], '
        'max_det=config["max_det"])'
        if family == "yolo26"
        else 'detector.detect(frame, conf_th=config["confidence"], '
        'iou_th=config["iou"], max_det=config["max_det"])'
    )
    return f'''"""Generated by AI Biaozhu."""
import json
import os
import time

from maix import app, camera, display, image, nn

APP_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(APP_DIR, "models", "model.mud")
CONFIG_PATH = os.path.join(APP_DIR, "config.json")

with open(CONFIG_PATH, "r", encoding="utf-8") as config_file:
    config = json.load(config_file)

cam = camera.Camera(config["camera"]["width"], config["camera"]["height"])
expected_ai_isp = config.get("ai_isp_mode", "not_applicable")
get_ai_isp_mode = getattr(cam, "get_aiisp_workmode", None)
if expected_ai_isp in ("disabled", "required") and callable(get_ai_isp_mode):
    actual_ai_isp = bool(get_ai_isp_mode())
    required_ai_isp = expected_ai_isp == "required"
    if actual_ai_isp != required_ai_isp:
        expected_text = "开启" if required_ai_isp else "关闭"
        raise RuntimeError(
            "当前 MaixCAM2 AI-ISP 模式与部署包不匹配；请在系统设置的 NPU "
            f"选项中{{expected_text}} AI-ISP，重启设备后再运行此 APP。"
        )
disp = display.Display()
detector = nn.{detector_class}(model=MODEL_PATH, dual_buff=config["dual_buff"])
last_frame_time = time.monotonic()
smoothed_fps = 0.0

while not app.need_exit():
    frame = cam.read()
    objects = {detect_call}
    for obj in objects:
        frame.draw_rect(obj.x, obj.y, obj.w, obj.h, color=image.COLOR_RED, thickness=2)
        labels = detector.labels
        label = labels[obj.class_id] if 0 <= obj.class_id < len(labels) else str(obj.class_id)
        frame.draw_string(obj.x, max(0, obj.y - 14), f"{{label}} {{obj.score:.2f}}")
    now = time.monotonic()
    frame_fps = 1.0 / max(now - last_frame_time, 1e-6)
    smoothed_fps = frame_fps if smoothed_fps <= 0 else smoothed_fps * 0.9 + frame_fps * 0.1
    last_frame_time = now
    frame.draw_string(4, 4, f"FPS {{smoothed_fps:.1f}}")
    disp.show(frame)
'''


def app_yaml(
    files: Iterable[str],
    *,
    app_id: str = "ai_biaozhu_detector",
    app_name: str = "AI Biaozhu Detector",
    version: str = "1.0.0",
) -> str:
    safe_files = tuple(_safe_relative(item) for item in files)
    lines = [
        f"id: {app_id}",
        f"name: {app_name}",
        f"version: {version}",
        "author: AI Biaozhu contributors",
        "desc: Object detector exported by AI Biaozhu",
        "files:",
    ]
    lines.extend(f"  - {item}" for item in safe_files)
    return "\n".join(lines) + "\n"


def _safe_relative(value: str) -> str:
    normalized = value.replace("\\", "/")
    if (
        not normalized
        or normalized.startswith("/")
        or ":" in normalized
        or any(part in {"", ".", ".."} for part in normalized.split("/"))
    ):
        raise ValueError(f"不安全的包内路径：{value!r}")
    return normalized
